version: 0.0
os: linux
files:
  - source: /PublicAPI/
    destination: /var/dotnetapp/source
  - source: /deployment/assets/dotnet.conf
    destination: /etc/httpd/conf.d/
  - source: /deployment/assets/kestrel-app.service
    destination: /etc/systemd/system/
hooks:
  ApplicationStop:
    - location: /deployment/scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: /deployment/scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: /deployment/scripts/build
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: /deployment/scripts/start_server
      timeout: 300
      runas: root
