version: 0.0
os: linux
files:
  - source: /PublicAPI/
    destination: /home/ubuntu/dotnetapp/source
hooks:
  AfterInstall:
    - location: /scripts/after_install
      timeout: 300
      runas: root
