version: 0.0
os: linux
files:
  - source: ../PublicAPI/
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: deployment/install_dependencies
      timeout: 300
      runas: root
    - location: deployment/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deployment/stop_server
      timeout: 300
      runas: root

