version: 0.0
os: linux
files:
  - source: /PublicAPI/
    destination: /var/www/html
  - source: /deployment/dotnet.conf
    destination: /etc/httpd/conf.d/dotnet.conf
hooks:
  ApplicationStop:
    - location: deployment/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: deployment/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: deployment/start_server
      timeout: 300
      runas: root
    - location: deployment/restore_packages
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deployment/run_application
      timeout: 300
      runas: root
