#!/bin/bash

## Install Apache
yum install -y httpd

# Copy Apache Dot Net Module for Reverse Proxy
sudo cp dotnet.conf /etc/httpd/conf/httpd.conf

## Install Dot Net Core
sudo yum install libunwind libicu
sudo curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?linkid=847103
sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
sudo ln -s /opt/dotnet/dotnet /usr/local/bin

## Instal Project Dependencies
dotnet restore ..\PublicAPI\