#!/bin/bash

# Restore Packages
sudo /usr/bin/dotnet restore /home/ubuntu/source

# Stop Service
sudo supervisorctl stop aspnetcore

# Build and Publish
sudo /usr/bin/dotnet publish /home/ubuntu/source -c Release -o /var/dotnetapp/

# Start Service
sudo supervisorctl start aspnetcore