#!/bin/bash

# Restore Packages
sudo /usr/bin/dotnet restore ~/dotnetapp/source

# Stop Service
sudo supervisorctl stop aspnetcore

# Build and Publish
sudo /usr/bin/dotnet publish ~/dotnetapp/source -c Release -o /var/dotnetapp/

# Start Service
sudo supervisorctl start aspnetcore