#!/bin/bash

# Restore Packages
sudo /usr/bin/dotnet restore /home/ubuntu/source

# Build and Publish
sudo /usr/bin/dotnet publish /home/ubuntu/source -c Release -o /var/dotnetapp/

# Start Service
supervisorctl reread
supervisorctl update
sudo supervisorctl start aspnetcore